# -*- coding: utf-8 -*-
"""EPICS23-056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17r8NwnWJaG5iD_I47Ic-jUmf6tDwnh7H
"""

"""
FSVI - Farm Shock Vulnerability Index
Agricultural Risk Assessment & Recommendation System
Sehore District, Madhya Pradesh
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────
# 1. DATA LOADING
# ─────────────────────────────────────────────
rain_df  = pd.read_excel('/mnt/user-data/uploads/rainfall.XLSX')
cpi_df   = pd.read_excel('/mnt/user-data/uploads/cpi.XLSX')
crop_df  = pd.read_excel('/mnt/user-data/uploads/crop.XLSX')
mkt_df   = pd.read_csv('/mnt/user-data/uploads/Merged_Season_Data_2021_to_2026.csv')

# ─────────────────────────────────────────────
# 2. NORMALISE YEAR STRINGS (homogenise separators)
# ─────────────────────────────────────────────
def norm_year(y):
    y = str(y).strip()
    for sep in [' - ', '–', '-']:
        if sep in y:
            parts = y.split(sep)
            yy = parts[1].strip() if len(parts[1].strip()) == 2 else parts[1].strip()[-2:]
            return f"{parts[0].strip()}-{yy}"
    return y

rain_df['Year'] = rain_df['Year'].apply(norm_year)
crop_df['Year'] = crop_df['Year'].apply(norm_year)
cpi_df['Year']  = cpi_df['Year'].apply(norm_year)
mkt_df['Year']  = mkt_df['Year'].apply(norm_year)

# ─────────────────────────────────────────────
# 3. HELPER: Min-Max normalise to [0,1]
# ─────────────────────────────────────────────
def minmax(series, invert=False):
    mn, mx = series.min(), series.max()
    if mx == mn:
        return series * 0.0
    norm = (series - mn) / (mx - mn)
    return 1 - norm if invert else norm

# ─────────────────────────────────────────────
# 4. WEATHER RISK SCORE  (per year × season)
# ─────────────────────────────────────────────
weather_rows = []
for _, r in rain_df.iterrows():
    for season, col in [('Kharif', 'Kharif Deviation (%)'), ('Rabi', 'Rabi Deviation (%)')]:
        dev = r[col]
        # High risk if very negative (<-30%) or very positive (>50%)
        if dev < -30:
            raw = abs(dev) / 100
        elif dev > 50:
            raw = dev / 100
        else:
            raw = max(0, -dev / 100)        # mild negative dev = mild risk
        weather_rows.append({'Year': r['Year'], 'Season': season, 'weather_raw': raw})

weather_df = pd.DataFrame(weather_rows)
weather_df['Weather_Risk'] = minmax(weather_df['weather_raw'])

# ─────────────────────────────────────────────
# 5. FINANCIAL STRESS SCORE
# ─────────────────────────────────────────────
cpi_df['fin_raw'] = cpi_df['Financial Stress Score'].clip(lower=0)
cpi_df['Financial_Risk'] = minmax(cpi_df['fin_raw'])

# ─────────────────────────────────────────────
# 6. YIELD RISK SCORE  (per crop × year)
# ─────────────────────────────────────────────
crop_df['hist_avg_yield'] = crop_df.groupby('Crop')['Yield (Tonne/Hectare)'].transform('mean')
crop_df['yield_shock'] = crop_df['hist_avg_yield'] - crop_df['Yield (Tonne/Hectare)']   # positive = worse
crop_df['yield_shock_pos'] = crop_df['yield_shock'].clip(lower=0)

# season tag per crop
def get_season(crop):
    return 'Rabi' if 'Rabi' in crop else 'Kharif'

crop_df['Season'] = crop_df['Crop'].apply(get_season)
crop_df['Yield_Risk_raw'] = minmax(crop_df['yield_shock_pos'])

# Aggregate to year × season level (avg across crops)
yield_agg = crop_df.groupby(['Year', 'Season'])['Yield_Risk_raw'].mean().reset_index()
yield_agg.rename(columns={'Yield_Risk_raw': 'Yield_Risk'}, inplace=True)

# ─────────────────────────────────────────────
# 7. PRICE RISK SCORE
# ─────────────────────────────────────────────
# For each commodity, compute price_ratio = actual_price / MSP
# ratio < 1 → high risk (farmer gets less than MSP)
price_rows = []
for _, r in mkt_df.iterrows():
    msp = r['MSP (Rs./Quintal)']
    if pd.isna(msp) or msp == 0:
        continue
    # Kharif
    if pd.notna(r['Kharif_Price']):
        ratio = r['Kharif_Price'] / msp
        risk_raw = max(0, 1 - ratio)          # below MSP = risk
        price_rows.append({'Year': r['Year'], 'Season': 'Kharif',
                           'Commodity': r['Commodity'], 'price_raw': risk_raw})
    # Rabi
    if pd.notna(r['Rabi_Price']):
        ratio = r['Rabi_Price'] / msp
        risk_raw = max(0, 1 - ratio)
        price_rows.append({'Year': r['Year'], 'Season': 'Rabi',
                           'Commodity': r['Commodity'], 'price_raw': risk_raw})

price_df = pd.DataFrame(price_rows)
price_df['Price_Risk_raw'] = minmax(price_df['price_raw'])
price_agg = price_df.groupby(['Year', 'Season'])['Price_Risk_raw'].mean().reset_index()
price_agg.rename(columns={'Price_Risk_raw': 'Price_Risk'}, inplace=True)

# ─────────────────────────────────────────────
# 8. MERGE ALL SCORES INTO MASTER TABLE
# ─────────────────────────────────────────────
master = pd.merge(weather_df[['Year', 'Season', 'Weather_Risk']],
                  cpi_df[['Year', 'Season', 'Financial_Risk']],
                  on=['Year', 'Season'], how='outer')

master = pd.merge(master, yield_agg, on=['Year', 'Season'], how='outer')
master = pd.merge(master, price_agg, on=['Year', 'Season'], how='outer')

# fill missing yield / price with column median
for col in ['Yield_Risk', 'Price_Risk', 'Weather_Risk', 'Financial_Risk']:
    master[col] = master[col].fillna(master[col].median())

# ─────────────────────────────────────────────
# 9. FSVI via PCA (data-driven weights from PC1)
# ─────────────────────────────────────────────
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

sub_scores = ['Price_Risk', 'Yield_Risk', 'Weather_Risk', 'Financial_Risk']
X = master[sub_scores].values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=1)
pc1_scores = pca.fit_transform(X_scaled).flatten()

# PC1 loadings (weights) — flip sign so higher = more risk
loadings = pca.components_[0]
# If most loadings are negative, flip the whole axis
if loadings.sum() < 0:
    loadings = -loadings
    pc1_scores = -pc1_scores

# Normalise PC1 scores to [0,1] so FSVI stays interpretable
pc1_min, pc1_max = pc1_scores.min(), pc1_scores.max()
master['FSVI'] = (pc1_scores - pc1_min) / (pc1_max - pc1_min)

# Store PCA metadata for reporting
pca_weights = dict(zip(sub_scores, loadings))
explained_var = pca.explained_variance_ratio_[0]

print(f"\n  PCA Explained Variance (PC1): {explained_var*100:.1f}%")
print("  PC1 Loadings (risk weights):")
for k, v in pca_weights.items():
    print(f"    {k:<20}: {v:.4f}")

# ─────────────────────────────────────────────
# 10. SHOCK LEVEL CLASSIFICATION
# ─────────────────────────────────────────────
def classify_shock(fsvi):
    if fsvi < 0.25:   return 'Low Risk 🟢'
    elif fsvi < 0.50: return 'Moderate Risk 🟡'
    elif fsvi < 0.75: return 'High Risk 🟠'
    else:             return 'Critical Risk 🔴'

master['Shock_Level'] = master['FSVI'].apply(classify_shock)
master['Dominant_Risk'] = master[sub_scores].idxmax(axis=1)

# ─────────────────────────────────────────────
# 11. RECOMMENDATION SYSTEM
# ─────────────────────────────────────────────
SCHEMES = {
    'Price_Risk': {
        'national': [
            "PM-AASHA (Pradhan Mantri Annadata Aay Sanrakshan Abhiyan) – MSP procurement guarantee",
            "e-NAM (National Agriculture Market) – digital mandi for better price discovery",
            "Warehouse Receipt System (WDRA) – store & sell at better price later",
        ],
        'state_mp': [
            "MP Bhavantar Bhugtan Yojana – compensates difference between MSP and market price",
            "MP State Agricultural Marketing Board (MSAMB) – improved mandi infrastructure",
            "Mukhyamantri Krishak Samridhi Yojana – price support for farmers in MP",
        ],
        'sehore': [
            "Sehore District Mandi (APMC) – direct MSP procurement for wheat & soybean",
            "Krishi Upaj Mandi Samiti, Sehore – register for MSP sale events",
        ],
        'microinsurance': [
            "Commodity Price Insurance (pilot by NCDEX & NABARD) – price floor protection",
        ],
        'crop_advice': "Consider wheat, Bengal gram — crops with strong MSP & active procurement in Sehore.",
    },

    'Yield_Risk': {
        'national': [
            "PM Fasal Bima Yojana (PMFBY) – subsidised crop insurance against yield loss",
            "RKVY (Rashtriya Krishi Vikas Yojana) – infrastructure & input support",
            "National Mission for Sustainable Agriculture (NMSA) – soil health & productivity",
            "Soil Health Card Scheme – free soil testing & fertiliser recommendations",
        ],
        'state_mp': [
            "MP Krishi Yantra Anudan Yojana – subsidy on farm machinery",
            "Mukhyamantri Khet Tirtha Yojana – farmer field school & demo plots",
            "MP Beej Anudan Yojana – subsidised certified seeds for HYV crops",
        ],
        'sehore': [
            "ATMA (Agriculture Technology Management Agency), Sehore – extension services & training",
            "Krishi Vigyan Kendra (KVK) Sehore – free seed distribution, soil testing, demos",
            "District Horticulture Office – subsidy for protected cultivation & fertigation",
        ],
        'microinsurance': [
            "PMFBY (Pradhan Mantri Fasal Bima Yojana) – enrol before season cutoff at nearest bank",
            "RWBCIS (Restructured Weather Based Crop Insurance) – weather-indexed yield protection",
        ],
        'crop_advice': "Shift to HYV soybean (JS-9560, NRC-37) or short-duration wheat (GW-496). Explore rice-wheat rotation.",
    },

    'Weather_Risk': {
        'national': [
            "PM Krishi Sinchai Yojana (PMKSY) – 'Har Khet Ko Pani' irrigation expansion",
            "National Watershed Development Project – rainwater harvesting & conservation",
            "National Adaptation Fund for Climate Change (NAFCC) – climate-resilient agriculture",
        ],
        'state_mp': [
            "MP Mukhyamantri Krishak Jeevan Kalyan Yojana – drought-related compensation",
            "Balram Talab Yojana (MP) – subsidy for farm pond construction",
            "MP Jal Mission – check-dam & lift-irrigation schemes in rain-shadow areas",
        ],
        'sehore': [
            "District Irrigation Dept, Sehore – Kolar & Parwati canal command area – check irrigation eligibility",
            "NABARD Watershed Projects in Sehore – soil-water conservation in upland villages",
        ],
        'microinsurance': [
            "RWBCIS (Weather Based Crop Insurance) – indexed against IMD rainfall data",
            "PMFBY – area-based yield cover triggered by drought / excess rain",
        ],
        'crop_advice': "Grow drought-tolerant soybean (JS-335), short-duration pulses, or sorghum in low-rainfall years.",
    },

    'Financial_Risk': {
        'national': [
            "Kisan Credit Card (KCC) – revolving crop credit at 4–7% interest",
            "PM Kisan Samman Nidhi – ₹6,000/year direct income support",
            "PM Kisan MaanDhan Yojana – pension scheme for small & marginal farmers",
            "Interest Subvention Scheme – short-term crop loans at concessional rate",
        ],
        'state_mp': [
            "MP Mukhyamantri Krishak Rin Mafi Yojana – loan waiver for eligible farmers",
            "MP Cooperative Bank crop loans – lower interest than commercial banks",
            "Mukhyamantri Yuva Swabhiman Yojana – employment & skilling support for farm households",
        ],
        'sehore': [
            "District Cooperative Central Bank (DCCB) Sehore – KCC, short-term crop loans",
            "NABARD refinance through Sehore DCCB – lower-cost credit to farmers",
            "CSC (Common Service Centre) Sehore – PM Kisan, KCC enrolment assistance",
        ],
        'microinsurance': [
            "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY) – affordable life cover for farmers",
            "Pradhan Mantri Suraksha Bima Yojana (PMSBY) – accidental death/disability cover ₹20/year",
        ],
        'crop_advice': "Reduce input-intensive crops. Explore legume intercropping to cut fertiliser costs.",
    },
}

def recommend(row):
    dom = row['Dominant_Risk']
    s = SCHEMES[dom]
    lines = [
        f"\n{'='*65}",
        f"  YEAR: {row['Year']}  |  SEASON: {row['Season']}",
        f"  FSVI: {row['FSVI']:.3f}  |  STATUS: {row['Shock_Level']}",
        f"  DOMINANT RISK DRIVER: {dom.replace('_', ' ')}",
        f"{'='*65}",
        f"\n  SUB-SCORES:",
        f"    Price Risk    : {row['Price_Risk']:.3f}",
        f"    Yield Risk    : {row['Yield_Risk']:.3f}",
        f"    Weather Risk  : {row['Weather_Risk']:.3f}",
        f"    Financial Risk: {row['Financial_Risk']:.3f}",
        f"\n  ► NATIONAL SCHEMES:",
    ]
    for sc in s['national']:
        lines.append(f"     • {sc}")
    lines.append(f"\n  ► MP STATE SCHEMES:")
    for sc in s['state_mp']:
        lines.append(f"     • {sc}")
    lines.append(f"\n  ► SEHORE DISTRICT SCHEMES:")
    for sc in s['sehore']:
        lines.append(f"     • {sc}")
    lines.append(f"\n  ► MICROINSURANCE OPTIONS:")
    for sc in s['microinsurance']:
        lines.append(f"     • {sc}")
    lines.append(f"\n  ► CROP ADVISORY:")
    lines.append(f"     {s['crop_advice']}")
    return '\n'.join(lines)

# ─────────────────────────────────────────────
# 12. BUILD OUTPUT EXCEL
# ─────────────────────────────────────────────
from openpyxl import Workbook
from openpyxl.styles import (Font, PatternFill, Alignment,
                              Border, Side, numbers)
from openpyxl.utils import get_column_letter

RISK_COLORS = {
    'Low Risk 🟢':      'C6EFCE',
    'Moderate Risk 🟡': 'FFEB9C',
    'High Risk 🟠':     'FFCC99',
    'Critical Risk 🔴': 'FFC7CE',
}
HEADER_FILL  = PatternFill('solid', start_color='1F4E79')
HEADER_FONT  = Font(name='Arial', bold=True, color='FFFFFF', size=11)
SUBHDR_FILL  = PatternFill('solid', start_color='BDD7EE')
SUBHDR_FONT  = Font(name='Arial', bold=True, size=10)
TITLE_FONT   = Font(name='Arial', bold=True, size=14, color='1F4E79')
BODY_FONT    = Font(name='Arial', size=10)
THIN_BORDER  = Border(
    left=Side(style='thin'), right=Side(style='thin'),
    top=Side(style='thin'),  bottom=Side(style='thin')
)

def set_header(ws, row, col, value):
    c = ws.cell(row=row, column=col, value=value)
    c.fill = HEADER_FILL; c.font = HEADER_FONT
    c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    c.border = THIN_BORDER

def set_body(ws, row, col, value, fill=None, num_fmt=None, bold=False):
    c = ws.cell(row=row, column=col, value=value)
    c.font = Font(name='Arial', size=10, bold=bold)
    c.alignment = Alignment(horizontal='center', vertical='center')
    c.border = THIN_BORDER
    if fill:
        c.fill = PatternFill('solid', start_color=fill)
    if num_fmt:
        c.number_format = num_fmt

wb = Workbook()

# ────────── SHEET 1 : FSVI Dashboard ──────────
ws1 = wb.active; ws1.title = 'FSVI Dashboard'
ws1.row_dimensions[1].height = 40
ws1.row_dimensions[2].height = 18

ws1.merge_cells('A1:J1')
title_cell = ws1['A1']
title_cell.value = 'FSVI – Farm Shock Vulnerability Index  |  Sehore, Madhya Pradesh'
title_cell.font = TITLE_FONT
title_cell.alignment = Alignment(horizontal='center', vertical='center')

headers = ['Year', 'Season', 'Price Risk', 'Yield Risk',
           'Weather Risk', 'Financial Risk', 'FSVI Score',
           'Shock Level', 'Dominant Risk', 'Recommendation']
for ci, h in enumerate(headers, 1):
    set_header(ws1, 3, ci, h)

master_sorted = master.sort_values(['Year', 'Season']).reset_index(drop=True)

for ri, row in master_sorted.iterrows():
    er = ri + 4
    shock = row['Shock_Level']
    bg = RISK_COLORS.get(shock, 'FFFFFF')
    dom_clean = row['Dominant_Risk'].replace('_Risk', '').replace('_', ' ')

    set_body(ws1, er, 1, row['Year'])
    set_body(ws1, er, 2, row['Season'])
    set_body(ws1, er, 3, round(row['Price_Risk'], 3),    num_fmt='0.000')
    set_body(ws1, er, 4, round(row['Yield_Risk'], 3),    num_fmt='0.000')
    set_body(ws1, er, 5, round(row['Weather_Risk'], 3),  num_fmt='0.000')
    set_body(ws1, er, 6, round(row['Financial_Risk'],3), num_fmt='0.000')
    set_body(ws1, er, 7, round(row['FSVI'], 3), fill=bg, num_fmt='0.000', bold=True)
    set_body(ws1, er, 8, shock, fill=bg, bold=True)
    set_body(ws1, er, 9, dom_clean)
    set_body(ws1, er, 10, recommend(row))
    ws1.row_dimensions[er].height = 14

ws1.column_dimensions['A'].width = 10
ws1.column_dimensions['B'].width = 9
for ci in range(3, 8): ws1.column_dimensions[get_column_letter(ci)].width = 14
ws1.column_dimensions['H'].width = 20
ws1.column_dimensions['I'].width = 18
ws1.column_dimensions['J'].width = 70

ws1.freeze_panes = 'A4'

# ────────── SHEET 2 : Recommendations Detail ──────────
ws2 = wb.create_sheet('Recommendations')
ws2.row_dimensions[1].height = 35
ws2.merge_cells('A1:F1')
ws2['A1'].value = 'Recommendations by Year, Season & Dominant Risk Driver'
ws2['A1'].font = TITLE_FONT
ws2['A1'].alignment = Alignment(horizontal='center', vertical='center')

rec_headers = ['Year', 'Season', 'FSVI', 'Shock Level', 'Dominant Risk Driver',
               'Recommended Schemes & Actions']
for ci, h in enumerate(rec_headers, 1):
    set_header(ws2, 2, ci, h)

for ri, row in master_sorted.iterrows():
    er = ri + 3
    shock = row['Shock_Level']
    bg = RISK_COLORS.get(shock, 'FFFFFF')
    dom_clean = row['Dominant_Risk'].replace('_Risk', '').replace('_', ' ')
    rec_text = recommend(row)

    set_body(ws2, er, 1, row['Year'])
    set_body(ws2, er, 2, row['Season'])
    set_body(ws2, er, 3, round(row['FSVI'], 3), fill=bg, num_fmt='0.000', bold=True)
    set_body(ws2, er, 4, shock, fill=bg, bold=True)
    set_body(ws2, er, 5, dom_clean)
    c = ws2.cell(row=er, column=6, value=rec_text)
    c.font = Font(name='Arial', size=9)
    c.alignment = Alignment(wrap_text=True, vertical='top')
    c.border = THIN_BORDER
    ws2.row_dimensions[er].height = 90

ws2.column_dimensions['A'].width = 10
ws2.column_dimensions['B'].width = 9
ws2.column_dimensions['C'].width = 10
ws2.column_dimensions['D'].width = 22
ws2.column_dimensions['E'].width = 22
ws2.column_dimensions['F'].width = 90

# ────────── SHEET 3 : Sub-Score Analysis ──────────
ws3 = wb.create_sheet('Sub-Score Analysis')
ws3.merge_cells('A1:E1')
ws3['A1'].value = 'Sub-Score Breakdown & FSVI Trend'
ws3['A1'].font = TITLE_FONT
ws3['A1'].alignment = Alignment(horizontal='center', vertical='center')

sh3_headers = ['Year', 'Season', 'Price Risk', 'Yield Risk',
               'Weather Risk', 'Financial Risk', 'FSVI',
               'Dominant Risk', 'Shock Level']
for ci, h in enumerate(sh3_headers, 1):
    set_header(ws3, 2, ci, h)
    ws3.column_dimensions[get_column_letter(ci)].width = 16

for ri, row in master_sorted.iterrows():
    er = ri + 3
    bg = RISK_COLORS.get(row['Shock_Level'], 'FFFFFF')
    vals = [row['Year'], row['Season'],
            round(row['Price_Risk'],3), round(row['Yield_Risk'],3),
            round(row['Weather_Risk'],3), round(row['Financial_Risk'],3),
            round(row['FSVI'],3),
            row['Dominant_Risk'].replace('_Risk','').replace('_',' '),
            row['Shock_Level']]
    for ci, v in enumerate(vals, 1):
        fmt = '0.000' if ci in [3,4,5,6,7] else None
        fill = bg if ci in [7,8,9] else None
        set_body(ws3, er, ci, v, fill=fill, num_fmt=fmt, bold=(ci==7))

# ────────── SHEET 4 : PCA Loadings ──────────
ws4 = wb.create_sheet('PCA Loadings')
ws4.merge_cells('A1:C1')
ws4['A1'].value = 'PCA – PC1 Loadings & FSVI Weights'
ws4['A1'].font = TITLE_FONT
ws4['A1'].alignment = Alignment(horizontal='center', vertical='center')
ws4.row_dimensions[1].height = 30

ws4.merge_cells('A2:C2')
ws4['A2'].value = f'PC1 explains {explained_var*100:.1f}% of total variance across the 4 sub-scores'
ws4['A2'].font = Font(name="Arial", italic=True, size=10, color="595959")
ws4['A2'].alignment = Alignment(horizontal='center')

pca_hdr = ['Sub-Score', 'PC1 Loading', 'Interpretation']
for ci, h in enumerate(pca_hdr, 1):
    set_header(ws4, 3, ci, h)
    ws4.column_dimensions[get_column_letter(ci)].width = [28, 16, 55][ci-1]

interp = {
    'Price_Risk':    'Higher loading → price weakness drives FSVI more',
    'Yield_Risk':    'Higher loading → yield shocks drive FSVI more',
    'Weather_Risk':  'Higher loading → rainfall extremes drive FSVI more',
    'Financial_Risk':'Higher loading → cost/CPI stress drives FSVI more',
}
sorted_weights = sorted(pca_weights.items(), key=lambda x: -abs(x[1]))
for ri2, (k, v) in enumerate(sorted_weights, 4):
    ws4.cell(row=ri2, column=1, value=k.replace("_", " ")).font = BODY_FONT
    c = ws4.cell(row=ri2, column=2, value=round(v, 4))
    c.font = Font(name="Arial", size=10, bold=True,
                  color="C00000" if v > 0.4 else ("375623" if v > 0.2 else "595959"))
    c.number_format = "0.0000"
    c.alignment = Alignment(horizontal="center")
    ws4.cell(row=ri2, column=3, value=interp[k]).font = BODY_FONT
    for ci2 in range(1, 4):
        ws4.cell(row=ri2, column=ci2).border = THIN_BORDER

ws4.merge_cells("A9:C9")
ws4["A9"].value = ("Note: FSVI = PC1 scores normalised to [0-1]. "
                   "Higher PC1 loading = that risk factor has more influence on FSVI. "
                   "Dominant Risk is still identified as the highest raw sub-score.")
ws4["A9"].font = Font(name="Arial", italic=True, size=9, color="595959")

# ────────── SHEET 5 : Raw Data ──────────
ws5 = wb.create_sheet('Raw Data')
ws5['A1'].value = 'Rainfall Data'
ws5['A1'].font = Font(bold=True, size=11, color='1F4E79')
for ci, col in enumerate(rain_df.columns, 1):
    set_header(ws5, 2, ci, col)
for ri, row in rain_df.iterrows():
    for ci, v in enumerate(row, 1):
        ws5.cell(row=ri+3, column=ci, value=v).font = BODY_FONT

ws5['H1'].value = 'CPI / Financial Data'
ws5['H1'].font = Font(bold=True, size=11, color='1F4E79')
for ci, col in enumerate(cpi_df.columns, 1):
    set_header(ws5, 2, ci+7, col)
for ri, row in cpi_df.iterrows():
    for ci, v in enumerate(row, 1):
        ws5.cell(row=ri+3, column=ci+7, value=v).font = BODY_FONT

# ─────────────────────────────────────────────
# SAVE
# ─────────────────────────────────────────────
out = '/mnt/user-data/outputs/FSVI_Report_Sehore_MP.xlsx'
wb.save(out)
print(f"✅  Saved: {out}")

# ─────────────────────────────────────────────
# 13. CONSOLE SUMMARY
# ─────────────────────────────────────────────
print("\n" + "="*65)
print("  FSVI SUMMARY  –  SEHORE, MADHYA PRADESH")
print("="*65)
print(master_sorted[['Year','Season','Price_Risk','Yield_Risk',
                       'Weather_Risk','Financial_Risk','FSVI','Shock_Level','Dominant_Risk']].to_string(index=False))

print("\n\n  ═══ LATEST SEASON RECOMMENDATION ═══")
latest = master_sorted.iloc[-1]
print(recommend(latest))